Update codeql-analysis-with-atm-query-suite.yml
Test updated Code Scanning mode

diff --git a/.github/workflows/codeql-analysis-with-atm-query-suite.yml b/.github/workflows/codeql-analysis-with-atm-query-suite.yml
--- a/.github/workflows/codeql-analysis-with-atm-query-suite.yml
+++ b/.github/workflows/codeql-analysis-with-atm-query-suite.yml
@@ -7,9 +7,10 @@ on:
   workflow_dispatch:
 
 env:
-  BASE_URL: 'https://atmcodeqlpublicdata.blob.core.windows.net/atmpublic/query-suite/threshold1-v0.0.3+adea502'
-  CLI_ADDITIONS_CHECKSUM: '9263bddb6eb2448eda5abce3ebd3e00852f4f0a618a7ea0b247dd3f011a876fc26b0616513b921f3a3a8ab8860a877b3db3b695d6e74b4d9bed2ffa8f55ba211'
-  QLPACK_CHECKSUM: 'a1f3fee75cef271aedafce21eb5ae5884427b3e7988fbba37643143d2f677036f3f364467941adb41691f9c1bb0c569ba5bb48abfea4c114541adc11a0673565'
+  BASE_URL: 'https://atmcodeqlpublicdata.blob.core.windows.net/atmpublic/query-suite/v1.0.1+a6aa602'
+  CLI_ADDITIONS_CHECKSUM: '6375e05e0326966e27bec63db61a92e56ebb563fe1aa67adc13c0262cbca55d7ddb6d13d5bd63c169b95b2cbe7cea5e5c560346c4302738724311a463735ef44'
+  MODEL_CHECKSUM: 'f0191c93957ccdfa27059c37ac08897f57e80e9660507dfbf40d826c13e78fd4'
+  QLPACK_CHECKSUM: 'a39bd8d90cfa39bf4f8a2c42481d7d22f3e04cc89451bde8eac98cc77688d3b42d6e9cc876e97314671c72c0d6d7a1405d6105202eb6377123b55ea188b6fac6'
 
 jobs:
   CodeQL-Build:
@@ -86,6 +87,17 @@ jobs:
 
           ls -lR ${cli_root}/lib-extra
           ls -lR ${cli_root}/ml-models
+          
+          echo "Model properties:"
+          cat ${cli_root}/ml-models/*.qlmodel/model.properties
+
+          echo "Checking that the model checksum matches the expected one defined in the 'env'" \
+            "property of the workflow definition"
+          if ! grep -q "checksum=${MODEL_CHECKSUM}" ${cli_root}/ml-models/*.qlmodel/model.properties; then
+            echo "::error::Failed to validate ATM model checksum. Expected checksum=${MODEL_CHECKSUM}, was" \
+              "$(grep 'checksum' ${cli_root}/ml-models/*.qlmodel/model.properties)"
+            exit 1
+          fi
 
       - name: Perform CodeQL Analysis
         uses: github/codeql-action/analyze@v1
